name: learn-github-actions
run-name: Run flutter analyze
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

    branches:
      - 'develop'

    paths-ignore:
      - '**.md'
      - 'doc/**'
      - '.git/'
      - '.vscode/'

jobs:
  initialize-flutter:
    uses: ./.github/workflows/flutter_init.yaml

  run-flutter-analyze:
    steps:
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
